-----

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
name: demo-app
namespace: flux-system
spec:
interval: 5m0s
path: ./apps/demo
prune: true
sourceRef:
kind: GitRepository
name: learning-flux
healthChecks:
- apiVersion: apps/v1
kind: Deployment
name: demo-app
namespace: default
timeout: 2m0s
